### ISSUE TITLE
set-env.sh / .bat should just activate the environment as default

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#10]
(environment already existing)
```
$ source set-env.sh 
No arguments supplied. Continuing with 'create' and 'install' as default
```

The typical case is to just activate the environment, i.e., the Python script should not do anything, I guess. 

The Yield an error if it does not exist (conda will probably do that automatically).

**Comment by philippmuller** [comment]
I adjusted this in the bash script and will do so in the batch script as well. If no options are supplied, the environment is activated. If there is no environment, conda will raise an error stating this and the script will tell the user to run again supplying 'create' and 'install' as arguments.
