### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by rbirkelbach** [hmgaudecker/econ-project-templates#11]
Dear all,

I get the following error. Does anyone know how I can fix this?
This happens also with a freshly pulled template on an OsX yosemite macbook pro. I already tried to reinstall anaconda (python 3) as well as sphinx+sphinxcontrib-bibtex. It creates a LaTeX document and a presentation. Any help is highly appreciated.
If you need further information from me, please tell me. Thanks a lot!

Best, Robert

Waf: Leaving directory `/Users/rbirkelbach/Documents/econ-project-templates/bld'
Build failed
Traceback (most recent call last):
  File "/Users/rbirkelbach/Documents/econ-project-templates/.mywaflib/waflib/Runner.py", line 287, in task_status
    return tsk.runnable_status()
  File "/Users/rbirkelbach/Documents/econ-project-templates/.mywaflib/waflib/Task.py", line 590, in runnable_status
    new_sig = self.signature()
  File "/Users/rbirkelbach/Documents/econ-project-templates/.mywaflib/waflib/Task.py", line 568, in signature
    self.sig_implicit_deps()
  File "/Users/rbirkelbach/Documents/econ-project-templates/.mywaflib/waflib/Task.py", line 759, in sig_implicit_deps
    (nodes, names) = self.scan()
  File "/Users/rbirkelbach/Documents/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 37, in scan
    msg, dummy, iterator = s.env.update(s.config, s.srcdir, s.doctreedir, s)
ValueError: too many values to unpack (expected 3)

**Comment by hmgaudecker** [comment]
Thanks. Had that before somewhere -- I probably upgraded Waf prematurely at some point and my sphinx builder is not compatible with that. I'll have a look at it tonight.

**Comment by hmgaudecker** [comment]
Should work again with the latest versions. Please re-open the ticket if it does not.

**Comment by rbirkelbach** [comment]
Many thanks, it works as expected! I highly appreciate the fast and kind support. Was it because some incompatible waf version?

**Comment by hmgaudecker** [comment]
Yes, I had updated Waf and did not check whether sphinx_build would still work.

**Comment by hmgaudecker** [comment]
For future reference: If you run into this because you updated Sphinx to 1.3.x in a project that had used Sphinx 1.2.x just:

* update Waf by replacing waf.py and .mywaflib with their latest versions from these templates
* adjust the contents of src/documentation/wscript with the latest version from these templates
