### ISSUE TITLE
Build failing with R project template

### ISSUE THREAD

**Issue by RoyalTS** [hmgaudecker/econ-project-templates#12]
I'm trying to get the R project template to run as is. So I forked this git repo and then cloned just the R branch using

    git clone -b R git@github.com:RoyalTS/econ-project-templates.git

Followed the instructions in the README, ran

    python waf.py configure
    python waf.py build

and eventually ran into the following error:

    Waf: Leaving directory `/Users/tobiasschmidt/Dropbox/research/econ-project-templates/bld'
    Build failed
    Traceback (most recent call last):
      File "/Users/tobiasschmidt/Dropbox/research/econ-project-templates/.mywaflib/waflib/Runner.py", line 287, in task_status
        return tsk.runnable_status()
      File "/Users/tobiasschmidt/Dropbox/research/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 346, in runnable_status
        ret = super(sphinx_build_task, self).runnable_status()
      File "/Users/tobiasschmidt/Dropbox/research/econ-project-templates/.mywaflib/waflib/Task.py", line 594, in runnable_status
        new_sig = self.signature()
      File "/Users/tobiasschmidt/Dropbox/research/econ-project-templates/.mywaflib/waflib/Task.py", line 572, in signature
        self.sig_implicit_deps()
      File "/Users/tobiasschmidt/Dropbox/research/econ-project-templates/.mywaflib/waflib/Task.py", line 763, in sig_implicit_deps
        (nodes, names) = self.scan()
      File "/Users/tobiasschmidt/Dropbox/research/econ-project-templates/.mywaflib/waflib/extras/sphinx_build.py", line 254, in scan
        doc_name + suffix for suffix in suffixes)))
    WafError: Could not find Sphinx document node at any of: 11 added, 0 changed, 0 removed.rst

What am I doing wrong?

**Comment by hmgaudecker** [comment]
I hope it's just the Sphinx version - the builder requires 1.3.x, I get this error with 1.2 as well:

```
pip install --upgrade sphinx==1.3
```
or similar with conda, whatever you happen to use.


There'll be an update which uses project-specific conda environments soon, that will fix this for good (in case this fixes your error).

**Comment by RoyalTS** [comment]
Sadly, that doesn't seem to be it. Upon `conda install sphinx` I get:

    # All requested packages already installed.
    # packages in environment at /Users/tobiasschmidt/anaconda:
    #
    sphinx                    1.3.1                    py27_0

**Comment by rbirkelbach** [comment]
Do you have Python 2 or 3 installed? You're supposed to run Python 3 if I recall correctly.

**Comment by RoyalTS** [comment]
2.7. The whole thing only works with Python 3?

**Comment by rbirkelbach** [comment]
Yes. I just looked it up here: http://hmgaudecker.github.io/econ-python-environment/
You can get the appropriate Anaconda distribution version here: http://repo.continuum.io/anaconda3 <http://repo.continuum.io/anaconda3>

I hope it helps!

**Comment by hmgaudecker** [comment]
I have not tried py2 in years... Sorry for the lack of documentation. Will
get fixed soon.
Am 12.09.2015 13:23 schrieb "Tobias Schmidt" <notifications@github.com>:

**Comment by RoyalTS** [comment]
No worries, but that crucial bit of information is indeed missing from the setup instructions. I guess I really should switch to Python 3.x sometime...

FWIW: If I set up a dedicated conda environment with Python 3.5 and `pip install sphinxcontrib-bibtex` (no conda package that's compatible with 3.5 yet, apparently) on top everything works as expected.

Thank you both for the quick help!
