### ISSUE TITLE
Default Stata path on Mac

### ISSUE THREAD

**Issue by RoyalTS** [hmgaudecker/econ-project-templates#13]
`run_do_script` seems to expect the Stata executable to be on the `PATH`, which on the Mac seems to me to be unnecessarily complicated. Can't it simply look for the executable in the one place it's likely to be, namely at `/Applications/Stata/StataSE.app/Contents/MacOS/` for StataSE (I assume the whole thing looks similar for the other Stata versions)?

**Comment by hmgaudecker** [comment]
Good idea -- feel free to open a pull request :-) Should not be hard.

If you are interested, some hints:

  * The code you will need to modify lives in
    .mywaflib/waflib/extras/run_do_script.py, lines 47-90
  * Please leave the current system in as the first option and the
    automatic search as a fallback (this is required if one wants to
    select a specific version)
  * Please make the pull request against the waf branch

**Comment by RoyalTS** [comment]
Yeah, I looked at those lines in the wee small hours of the morning and couldn't quite figure it out. Now, with fresh eyes:

Not sure this is how you imagine it working, but simply taking the commands that are already in STATA_COMMANDS, generating full paths from them and adding them back into STATA_COMMANDS works for me. I.e. after line 52, add

    	APP_PATHS = ['/Applications/Stata/%s.app/Contents/MacOS/%s' % (sv, sv)
				 for sv in STATA_COMMANDS]
	STATA_COMMANDS += APP_PATHS

*prepares_for_a shellacking_from_the Pythonistas* =)

**Comment by hmgaudecker** [comment]
Looks good to me, thanks!

If it works for you, it should work for most people -- luckily, most 
Macs are alike...

**Comment by RoyalTS** [comment]
Cool! Do you want to patch this yourself or should I make a pull request?

**Comment by hmgaudecker** [comment]
On 21.09.15 11:38, Tobias Schmidt wrote:
> Cool! Do you want to patch this yourself or should I make a pull request?
Would be nice to have the latter... Thanks!

I'll hopefully update the entire material later this week.

**Comment by hmgaudecker** [comment]
Closed by #14
