### ISSUE TITLE
combine conda/pip package management

### ISSUE THREAD

**Issue by RoyalTS** [hmgaudecker/econ-project-templates#16]
More of a question than an issue perhaps: Why is it you're separating the management of packages installed via conda from those installed via pip? E.g. in `set-env.sh` you first read in a txt generated via `conda list --export > conda_versions.txt` and then `pip install` the packages listed in `requirements.txt`).

Why not let conda handle all of it? Couldn't you export the entire environment using `conda env export > environment.yml` (http://conda.pydata.org/docs/commands/env/conda-env-export.html), which outputs not just the packages installed via conda but also those installed via pip, and re-create that environment using `conda env create -f environment.yml`?

**Comment by hmgaudecker** [comment]
Nice. Seems to be a new feature, I remember some discussion on that, but I'm pretty sure it wasn't implemented in spring/summer... 

@philippmuller, can you change that, please?

**Comment by philippmuller** [comment]
Adjusted set-env.bat
