### ISSUE TITLE
Errors in Python-variant

### ISSUE THREAD

**Issue by felixpoege** [hmgaudecker/econ-project-templates#22]
Dear Mr. Gaudecker,

recently I cloned a fresh version of the Python module and when running it now, several errors occurred.

First, the first Python file to be executed did not find the project_paths.py file, which I solved by adding an empty `__init__.py` file in the same directory. Maybe waf should do that by itself?

Second, it seems to me that there is a small coding mistake.  In schelling.py and plot_locations.py, it seems that the line
`model = json.load(open(ppj("IN_MODEL_SPECS", model_name + ".json"), encoding="utf-8"))`
should actually be
`model = json.load(open(ppj("IN_MODEL_SPECS", model_name + ".json")), encoding="utf-8")`

The third error, which I am not able to solve right now, is that waf sends the following message:
`WafError: Could not find Sphinx document dependency node: C:\Users\...\pythontemplate\src\paper\refs.bib`
Is there some fix for this? I don't really know where to start debugging it as the file exists and the path to the file is correct. Of course, when I remove the reference to the bibliography, everything works just fine.

I would highly appreciate any help. Thank you!

Best regards,
Felix

**Comment by hmgaudecker** [comment]
Which versions of python / sphinx are you using?

Am 06.04.2017 10:19 vorm. schrieb "felixpoege" <notifications@github.com>:

**Comment by felixpoege** [comment]
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] and sphinx-1.4.6-py2.7

**Comment by hmgaudecker** [comment]
Thanks. I should note somewhere that only python 3 is supported, that
should explain the first two issues for sure. Will see about the third.

Am 06.04.2017 11:19 vorm. schrieb "felixpoege" <notifications@github.com>:

**Comment by felixpoege** [comment]
Okay, it seems that the switch to Python 3.6 has resolved the third issue as well. Thanks!
