### ISSUE TITLE
Add documentation for Stata / R

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#28]

**Comment by raholler** [comment]
So what exactly is to do here? Adapting the rationale.rst text to the stata/R example? Anything else particular for Stata and R that needs changing?

**Comment by hmgaudecker** [comment]
All the text should currently refer to the Schelling example; this should be the AJR example instead.

Else, please have a good look of whether things are comprehensible etc., this may well spill over to the Python example.

**Comment by raholler** [comment]
#60

**Comment by raholler** [comment]
So I looked into readthedocs builder, I don't think it is easy (possible) to use waf instead of plain sphinx. So would it be a viable solution to set bld/example under version control when you want to publish a new version?

**Comment by hmgaudecker** [comment]
Sure, no problem!
