### ISSUE TITLE
Make graphs for documentation of Stata branch

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#32]
Same as for the current Python branch docs, main graph here:

http://hmgaudecker.github.io/econ-project-templates/_images/schelling_dependencies.png

Instead of the Schelling example, use the AJR / Albouy example as detailed in the code documentation of the Stata branch (will need to follow what the wscript files are doing).

Needs to be done before @hmgaudecker gets started on #28

**Comment by hmgaudecker** [comment]
That is, adjust all files source/examples/schelling*.tex in gh-pages branch, rename schelling -> ajrcomment

**Comment by julienschat** [comment]
The graphs are created (7ccbd785f3f32a894ea78210363cf674103faa2b) and partitioned into main, data, final and paper in different files. Is the partition now as expected?

**Comment by hmgaudecker** [comment]
Looks great, thanks!
