### ISSUE TITLE
Re-enable conda_environment creation once conda 4.6 is out

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#35]
See: https://github.com/conda/conda/pull/7206.

Disabled in 18e2fcfd849a2620fb, will need to revert that.

**Comment by hmgaudecker** [comment]
Also check on Windows 10 -- for old versions, apparently ``START set-env.bat`` was required instead of ``set-env.bat``

**Comment by julienschat** [comment]
Conda environments are reenabled (b3943da1f918f2cb72b7f9ea5252186018b018c4) and I updated the documentation for python in gh-pages, now waiting to be adopted in the documenation on Stata/R. I also introduces the variable python version again, was that planned anyway?

**Comment by julienschat** [comment]
> Also check on Windows 10 -- for old versions, apparently `START set-env.bat` was required instead of `set-env.bat`

Why do you mention the old set-env.bat story?

**Comment by hmgaudecker** [comment]
> > Also check on Windows 10 -- for old versions, apparently `START set-env.bat` was required instead of `set-env.bat`
> 
> Why do you mention the old set-env.bat story?

Good question. More as a reminder to check across different OS's and probably because somebody mentioned it to me at that point.

> I also introduced the variable python version again, was that planned anyway?

Yes, sounds good. Although we should restrict to >= 3.6 and mention that in the README where we list / explain the options.

Thanks

**Comment by julienschat** [comment]
Restriction is set up in the pre hook cb0dcf24b4d3d018d6cddd83f41abe6f308a5caa.

**Comment by hmgaudecker** [comment]
Great, thanks! 

@raholler: Once we have a consistent way of doing things on Windows, we should also activate the environment.

**Comment by raholler** [comment]
what else is there to be fixed for windows?
- Install Anaconda for all Users, if possible, and add respective folder to path -> python can be run from powershell.
- For conda >= 4.6, run conda init in your favorite shell, then one can use conda environments as described by anaconda

**Comment by hmgaudecker** [comment]
Nothing, I guess. We just need to note this bold and center in the Readme. Currently, the order of 1. and 2. is not great, either -- cookiecutter should go in the Anaconda Python.

So: 

1. Prerequisites
  - latex
  - install miniconda or anaconda -- on Windows, do this for all users and run conda init ("add respective folder to path" -- is that an option during the installation? 
  - run pip install cookiecutter
  - make sure git can be found in shell (I had a bunch of people reporting errors because this was not set up)

2. [Continue with what is currently 3. https://github.com/hmgaudecker/econ-project-templates#getting-started]

**Comment by raholler** [comment]
-- is that an option during the installation? Theoretically yes, but was not reliably working in the past. Need to check whether this has changed with the recent conda update.

Regarding git: I am not aware of any issues using powershell and git. Was always working perfectly for me. Do you remember any names/contact of any people running into this issue?

Is there a viable reason why the current reimplementation has the default to create a conda environment. I think for non-python casual users, it may come with too much overhead.

**Comment by raholler** [comment]
Right now, yields:

> ModuleNotFoundError: No module named 'sphinx_build'

 when running build step of the python example while prespecified environment ist specified.

**Comment by raholler** [comment]
@hmgaudecker why is jupyter lab a dependency, why is pytest* a dependency?

**Comment by hmgaudecker** [comment]
> -- is that an option during the installation? Theoretically yes, but was not reliably working in the past. Need to check whether this has changed with the recent conda update.

It probably won't have changed, tried it yesterday in trying to get the pre-commit stuff to run out of the box. We should add a print statement at the end saying that the environment needs to be activated, that would be lost in the middle of the commit etc., otherwise.

> Regarding git: I am not aware of any issues using powershell and git. Was always working perfectly for me. Do you remember any names/contact of any people running into this issue?

One probably has to specify something like that explicitly in the installation process. I can try it out on my VM next week.

> Is there a viable reason why the current reimplementation has the default to create a conda environment. I think for non-python casual users, it may come with too much overhead.

Default is always 1=yes, no way to change that without having the coding reversed, unfortunately. Unless cookiecutter has gotten more flexible.

**Comment by hmgaudecker** [comment]
> Right now, yields:
> 
> > ModuleNotFoundError: No module named 'sphinx_build'
> 
> when running build step of the python example while prespecified environment is activated.

Worked yesterday, hmmm... Version of Sphinx? I saw 2.0 was out a week ago, maybe it has made its way into conda and that broke it?

**Comment by hmgaudecker** [comment]
> Right now, yields:
> 
> > ModuleNotFoundError: No module named 'sphinx_build'
> 
> when running build step of the python example while prespecified environment is activated.



> @hmgaudecker why is jupyter lab a dependency, why is pytest* a dependency?

Jupyterlab because of the sandbox.

pytest mainly for the tests of the environment itself. But we should add a couple, too, to have a place to start from.

**Comment by raholler** [comment]
> 
> 
> > Right now, yields:
> > > ModuleNotFoundError: No module named 'sphinx_build'
> > 
> > 
> > when running build step of the python example while prespecified environment is activated.
> 
> Worked yesterday, hmmm... Version of Sphinx? I saw 2.0 was out a week ago, maybe it has made its way into conda and that broke it?

Seems indeed to be the problem. When setting sphinx to version 1.8.5, the error disappears.

**Comment by raholler** [comment]
> 
> 
> > Right now, yields:
> > > ModuleNotFoundError: No module named 'sphinx_build'
> > 
> > 
> > when running build step of the python example while prespecified environment is activated.
> 
> > @hmgaudecker why is jupyter lab a dependency, why is pytest* a dependency?
> 
> Jupyterlab because of the sandbox.
> 
> pytest mainly for the tests of the environment itself. But we should add a couple, too, to have a place to start from.

Do you mean, you want to add tests to the exisitng example?
