### ISSUE TITLE
Fix paths in all templates

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#39]
The project paths set in the main dictionary were different across branches and Tobias made changes relative to what the other languages expect. This is a huge mess currently and needs to be cleared up very soon.

**Comment by julienschat** [comment]
Can you specify which languages in the cookiecutter template had path related errors so far?

**Comment by hmgaudecker** [comment]
All of them except for Python. 

Please look at the main wscript files in the original branches and consider the function e.g. for [Python](https://github.com/hmgaudecker/econ-project-templates/blob/python/wscript) or [Stata](https://github.com/hmgaudecker/econ-project-templates/blob/stata/wscript). This is **exactly** what they need to look like after cookiecutter is done.

 Some comments:

* In the current cookiecutter version, there is stuff like `IN_DATA_EXTERNAL`, `IN_DATA_PROCESSED`, `IN_DATA_RAW`. These just needs to be `IN_DATA` again. Same for all places where this is used in wscript files and actual code.
* The block below `# Convert the directories into Waf nodes.` should be taken from the Stata branch.
* `LiBRARY` should be present in all templates, `OUT_LIBRARY_R` can go thanks to  416e2a71f2
* The part `# Stata's adopaths get special treatment.` should end up in the downloaded version if and only if `configure_running_stata_from_waf` is set to True or the Stata example is being installed (code for that now at the bottom of wscript).
