### ISSUE TITLE
Add sphinx autodoc for Matlab

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#43]
* install sphinxcontrib-matlabdomain via pip in environment if both configure_running_matlab_from_waf and configure_running_sphinx_from_waf are set to True.
* Then make documentation of functions etc exactly the same as in Python example
* See the code by @gehringl for how to do that.

**Comment by hmgaudecker** [comment]
https://github.com/gehringl/Aiyagari_LGR18

**Comment by julienschat** [comment]
Autodoc should work now with Matlab, see commit 0cf92f97a986a2e0d72945103f6287e6c4718f3f. The documentation looks like this: 
[project_documentation.pdf](https://github.com/hmgaudecker/econ-project-templates/files/2941425/project_documentation.pdf)
I included the bib file as you did in the python documentation, but what is it for?

**Comment by hmgaudecker** [comment]
> Autodoc should work now with Matlab, see commit [0cf92f9](https://github.com/hmgaudecker/econ-project-templates/commit/0cf92f97a986a2e0d72945103f6287e6c4718f3f) and [b06c825](https://github.com/hmgaudecker/econ-project-templates/commit/b06c825e674219ed9779a4785850b529b00d942e). The documentation looks like this: [project_documentation.pdf](https://github.com/hmgaudecker/econ-project-templates/files/2941425/project_documentation.pdf)

Thanks, looks great! A couple of comments:

- Are the automodule directives necessary? / what do they do?
- Would be great to include a link to the Matlab autodoc documentation

> I included the bib file as you did in the python documentation, but what is it for?

- You mean at the very end in references.rst? This is for things like " :cite:`StachurskiSargent13`" to work.

**Comment by julienschat** [comment]
Autodoc has to know which module (in this case directory) the file is to be found in. This is solves via the automodule specification.

**Comment by hmgaudecker** [comment]
Cool, maybe add a comment before those lines:

.. Matlab autodoc needs to know where to find the functions that are documented in the following  

and then close.

**Comment by julienschat** [comment]
Comment was added in df3f671dcda36268b0bbaf9ee85785ef76b68fdc.
