### ISSUE TITLE
Waf build raises: "RuntimeError: generateor raised StopIteration" for Python 3.7

### ISSUE THREAD

**Issue by tobiasstenzel** [hmgaudecker/econ-project-templates#45]
Waf build failed for Python 3.7 but worked after downgraded to 3.6.7. 

Reason: PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (https://docs.python.org/3/whatsnew/3.7.html) 

The exact location of the problem can be found when waf building in 3.7 environment.

**Comment by hmgaudecker** [comment]
Thanks. I cannot reproduce this behaviour, it looks like something that I remember from older Waf versions. Which branch / revision are you using?

**Comment by tobiasstenzel** [comment]
(Excuse the late reply, I felt sick the last days...) What do you exactly mean by branch/revision?

**Comment by hmgaudecker** [comment]
> What do you exactly mean by branch/revision? Of what?

Of this repository.

If you were talking about a project of yours that you started before September 2018, then you would need to copy waf.py and the entire .mywaflib folder from the current templates here in order to make it work with Python 3.7.

**Comment by tobiasstenzel** [comment]
Unfortunately I tried to run your most recent version of this template. I update my python again and try to provide more information on the error.

**Comment by tobiasstenzel** [comment]
Okay, apparantely I cannot reproduce this error either because I get different errors now that are very time-consuming to solve. I would regard that issue as closed now because at least I stated a way to solve around.
