### ISSUE TITLE
Get Python Example to Run, EPP Course

### ISSUE THREAD

**Issue by relaxxoo** [hmgaudecker/econ-project-templates#46]
After following the steps from Getting Started, I am still unable to get the python example to run. I am using Windows 10 Pro and the Anaconda Prompt. python waf.py configure works. However, **python waf.py build gives the following error message: No module named 'sphinxcontrib.bibtex'**.  (I did not check the box for sphinx, as far as I can tell)

I already tried the following: 

- Updating Sphinx
- Updating Miktex

pip install sphinxcontrib-bibtex did the trick.

**Comment by hmgaudecker** [comment]
Thanks! 

Closing this as it was noted in the installation guide: http://hmgaudecker.github.io/econ-python-environment/additional_python_libraries.html and I had also updated the readme on Tuesday: https://github.com/hmgaudecker/econ-project-templates#additional-prerequisites
