### ISSUE TITLE
Update howto-release

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#53]
There is a branch "z-howto-release", this should probably just be a file in the gh-pages branch which is not shown publicly among the rendered pages. No idea whether it is up-to-date. 

After moving over, the branch can be deleted.

As noted in dbe9ca671, please add that one step will be to add a set of versions to the environment.yml file which is up-to-date and known to be working at the time.

**Comment by raholler** [comment]
Is this still a current issue, should I integrate "z-how-to-release" in the master branch?

**Comment by hmgaudecker** [comment]
Yes, please. Thanks!
