### ISSUE TITLE
Conda environment has problems installing the pip packages upon first creation

### ISSUE THREAD

**Issue by raholler** [hmgaudecker/econ-project-templates#56]
Right now, conda enivronment is automatically installed on the system. But somehow, during this first installment, the packages listed under pip are not installed. I always have to update the conda environment from file for them to be properly installed.

**Comment by hmgaudecker** [comment]
Works for me on pre-commit branch. Conda 4.6.9 and 4.6.12, Ubuntu 18.04.

**Comment by raholler** [comment]
Most propbably a windows problem. The use of conda environments is still not really stable according to several issues posted at conda. Further, it depends on the conda version. Apparently, newer updates break the use again. I will investigate it further.
