### ISSUE TITLE
pre-commit hooks fail in windows

### ISSUE THREAD

**Issue by Eric-Sommer** [hmgaudecker/econ-project-templates#58]
Potentially related to Issue #57 
Committing fails in my setting (Windows 10 machine), unless I circumvent the commit hook. Apparently, some `pip` routine fails. See the log below.

It is striking that there is no `py_env-python3.7` folder in `z:\.cache\pre-commit\repod5i_j8ft\`. I don't think is is a permission issue, since I have full permissions on the `Z:` drive.

    (dynamod)` W:\izamod\dyn\izadynmod>git commit -m "some message"
    [INFO] Locking pre-commit directory
    [INFO] Installing environment for https://github.com/ambv/black. 
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: Command: ('Z:\\.cache\\pre-commit\\repod5i_j8ft\\py_env-python3.7\\Scripts\\pip.exe', 'install', '.')

    Return code: 1
    Expected return code: 0
    Output:
    Processing z:\.cache\pre-commit\repod5i_j8ft
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    Errors:
    ERROR: Complete output from command 'z:\.cache\pre-commit\repod5i_j8ft\py_env-python3.7\scripts\python.exe' 'z:\.cache\pre-commit\repod5i_j8ft\py_env-python3.7\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\iza6354\AppData\Local\Temp\pip-build-env-6o1cigzy\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel:

      ERROR: Collecting setuptools>=40.8.0

        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026A3668BE80>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed')': /simple/setuptools/

        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026A366A50B8>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed')': /simple/setuptools/

        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026A366A50F0>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed')': /simple/setuptools/

        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026A366A5390>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed')': /simple/setuptools/

        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000026A366A5400>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed')': /simple/setuptools/

        ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)

      ERROR: No matching distribution found for setuptools>=40.8.0

      ----------------------------------------

    ERROR: Command "'z:\.cache\pre-commit\repod5i_j8ft\py_env-python3.7\scripts\python.exe' 'z:\.cache\pre-commit\repod5i_j8ft\py_env-python3.7\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\iza6354\AppData\Local\Temp\pip-build-env-6o1cigzy\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel" failed with error code 1 in None
    Check the log at Z:\/.cache\pre-commit\pre-commit.log

**Comment by hmgaudecker** [comment]
@raholler - Any ideas? This is beyond my knowledge of Windows... I suspected a permissions issue given the `--no-user' option, but probably this is not it?

**Comment by raholler** [comment]
Which shell do you use? Do you have administrator priveledge? What is your pre-commit version? Can you execute normal python scripts from your shell? 
For me it works for Windows 10 with Powershell.

**Comment by Eric-Sommer** [comment]
> Which shell do you use? 
PowerShell, WindowsCMD, Anaconda Prompt, Git bash. All fail :)
> What is your pre-commit version? 
1.17.0
> Can you execute normal python scripts from your shell?
yes.

**Comment by Eric-Sommer** [comment]
I found the [solution](https://github.com/pre-commit/pre-commit/issues/960).  As a workaround, one should `set HOME=%USERPROFILE%`. might become obsolete with python3.8 if I understand it correctly

**Comment by pauschae** [comment]
Thanks a lot Eric this really helped me. For me the work-around lead to the problem that other libraries could no longer find their dependencies.  But after re-installing anaconda this worked again.
