### ISSUE TITLE
Add pyupgrade to pre-commit hooks.

### ISSUE THREAD

**Issue by tobiasraabe** [hmgaudecker/econ-project-templates#59]
I find it extremely useful to automatically upgrade my code to newer syntax. You can pass different flags to [``pyupgrade``](https://github.com/asottile/pyupgrade), ``--py3-plus`` or even ``--py36-plus``, if you limit yourself to specific Python versions.

**Comment by raholler** [comment]
How good does this actually work?

**Comment by hmgaudecker** [comment]
I think this looks actually pretty neat. Let us please add it with the `--py37-plus` - option
