### ISSUE TITLE
Prepare for release 0.2

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#61]
- [x] Make sure RTD versioning works as expected - point to stable, possibility to get to master (https://docs.readthedocs.io/en/stable/versions.html) with relevant differences in where cookiecutter points to.
- [x] Add release notes MD / RST file (finally a place to adequately thank all those helpers), link in docs (possible if in main folder? else just in docs?) 
- [x] put bld/examples under version control
- [x] Move docs of 0.1 release to RTD, too, if possible.
- [ ] Tag release
- [ ] Get specific Zenodo DOI (IIUC, see http://help.zenodo.org/#versioning) and force push to tag with that citation for front page / license of docs.
- [ ] Put in redirect only on gh-pages
- [x] Make sure everything from current README is on RTD landing page, put link to RTD in README and add some notes that this part is mainly for developers.

**Comment by raholler** [comment]
Move docs of 0.1 release to RTD, too, if possible: Probably possible, (force put tag?) Will try.

Make sure everything from current README is on RTD landing page: is in quickstart

some notes that this part is mainly for developers: should I put how to-release in the README?

finally a place to adequately thank all those helpers: can you be more precise what/who you mean? Should this go on the README or in the docs?

Get specific Zenodo DOI (IIUC, see http://help.zenodo.org/#versioning) and force push to tag with that citation for front page / license of docs: also for the old version?

**Comment by raholler** [comment]
So the transformed version of the v0.1 docs is ready to be committed to the tag. Then we could test the readthedocs configuration with this version. (only added docs folder, and changed a README). Are you okay with that?

**Comment by hmgaudecker** [comment]
> So the transformed version of the v0.1 docs is ready to be committed to the tag. Then we could test the readthedocs configuration with this version. (only added docs folder, and changed a README). Are you okay with that?

Yes, sounds great! Maybe add a big fat line saying: "This version of the documentation is left online only for historical reasons; please work with it only if you started using a template between January and July 2019."

**Comment by hmgaudecker** [comment]
> Make sure everything from current README is on RTD landing page: is in quickstart

+1

> some notes that this part is mainly for developers: should I put how to-release in the README?

+1

> finally a place to adequately thank all those helpers: can you be more precise what/who you mean? Should this go on the README or in the docs?

I thought many projects had some release notes section, maybe look at that.

> Get specific Zenodo DOI (IIUC, see http://help.zenodo.org/#versioning) and force push to tag with that citation for front page / license of docs: also for the old version?

Should be around already. IIUC, https://doi.org/10.5281/zenodo.2533240 is the general one and http://doi.org/10.5281/zenodo.2533241 the one for 0.1

**Comment by raholler** [comment]
https://econ-project-templates.readthedocs.io/en/stable/index.html

**Comment by hmgaudecker** [comment]
Cool, thanks! 

Small comments:

- The link here at "getting started" does not resolve Follow the guide listed in the Readme file inlcuded at the :ref:`beginning readme`. 
- Simple solution (sorry for the conflicting requests...): As we do not want anyone to get started with this version, just delete entire sections: 

  - README/Templates for... [just leave the first paragraph]
  - R / Stata example [misleading, just repeats py/m]
  - Getting started

For v0.2:

- I restructured quite a bit of stuff in 6be0c2f
- E.g., the "Getting started" section (i.e., the one that appeared in the sidebar) was outdated (still lived in pre-cookiecutter era), we had some conflicting advice for novices, etc.
- I was not sure about the "Prerequisites" and "To run the R example" sections of the Getting Started chapter. We should signal for the former that this is only for the case of not having a conda environment already in the heading. For the R example: Is that still relevant after all your work?
- Please check thoroughly whether the whole thing seems coherent. Thanks!

**Comment by raholler** [comment]
I am against deleting the README section. That is actually the only relevant section of this doc, because the dialog started by cookicutter has changed dramtically. Everything else is super similar. 

Regarding the R example: true forgot about that. I looked it up and it was not transparant to me at all why the package ivpack is even loaded, because all the functions are defined in functions.r which does not rely on ivpack. In the R language, however, it is not transparant where packages are called. I wanted to try removing it and see what happens -> will do

Anyway I would leave the prerequesites in there anyways. I think it is transparent and the maintenance is minimal. 

I am out until the weekend, next update comes sunday.

**Comment by hmgaudecker** [comment]
> I am against deleting the README section. That is actually the only relevant section of this doc, because the dialog started by cookicutter has changed dramtically. Everything else is super similar.

Fair enough. But let us get rid of the getting started below and maybe adjust the headings a bit (e.g. remove the one from the copied README)

> Regarding the R example: true forgot about that. I looked it up and it was not transparant to me at all why the package ivpack is even loaded, because all the functions are defined in functions.r which does not rely on ivpack. In the R language, however, it is not transparant where packages are called. I wanted to try removing it and see what happens -> will do

Sounds good. 

> Anyway I would leave the prerequesites in there anyways. I think it is transparent and the maintenance is minimal.

Yes, I did not want to suggest removing it, just to signal already in the heading that it is only relevant for those who did not opt for a conda environment.
 
> I am out until the weekend, next update comes sunday.

Fine, no rush!

**Comment by raholler** [comment]
our documentation is not correctly build, put an issue on: https://github.com/readthedocs/readthedocs.org/issues/6064

**Comment by raholler** [comment]
- R example is working without ivpack. Thus conda environment suffices to run the r example. Will update the docs accordingly.
- To clarify: I looked up release notes, and I do not think that s what you want. Do you want me to add a thank you section to the docs? Do you want to add everybody who ever contributed?
- I would also add the how to release stuff under a section "For Developers" to the docs.

**Comment by hmgaudecker** [comment]
Sounds great!

R release notes: I did mean that, just a document listing what had changed from one version to another. We can add who contributed what etc then. I will write that part then once the "machinery" is in place.

**Comment by hmgaudecker** [comment]
@raholler: Can you please do the checks here:

file:///home/hmg/econ/econ-project-templates/docs/bld/developer.html#pre-release-tasks-checks

And add a few more specifics to those docs (e.g. versions should probably only be Python 3.7, Numpy 1.17 etc., not more detailed; where exactly change pre-commit hooks etc.). Please push to master directly.

**Comment by raholler** [comment]
> 
> 
> @raholler: Can you please do the checks here:
> 
> file:///home/hmg/econ/econ-project-templates/docs/bld/developer.html#pre-release-tasks-checks
> 
> And add a few more specifics to those docs (e.g. versions should probably only be Python 3.7, Numpy 1.17 etc., not more detailed; where exactly change pre-commit hooks etc.). Please push to master directly.

I somehow missed this remark. And of course did not put versions in environment... sorry, shall I push that into the tag?

**Comment by hmgaudecker** [comment]
Yeah, no worries, I did not set a doi link yet. Thanks!
