### ISSUE TITLE
Re-enable --shell-escape for LaTeX

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#64]
Similar to f7bb61b5166e, but for main wscript. Was there any reason to disable it that I cannot remember? Leaving it on is crucial for the Stata template because the only thing Stata consistently produces are eps-files and they need conversion to pdf before being useful to pdflatex.

**Comment by raholler** [comment]
we disabled it for azure, is it an option to save the stuff as png instead of eps, or directly as pdf (do we need shell escape then?)

**Comment by hmgaudecker** [comment]
No, at least older versions of Stata relied on some library to generate pngs that was only available as GUI... Maybe they took the graph they displayed and made a screenshot :-)

So we should leave the comment where it is unless we are using the Stata example.

**Comment by raholler** [comment]
i am pretty sure, stata 13 at least already supports png, do we really need to care for older versions?

**Comment by hmgaudecker** [comment]
Yes, but to my best recollection only the GUI version of Stata, not the command line version, which is what we need.

**Comment by raholler** [comment]
fixed in #65

**Comment by hmgaudecker** [comment]
Just for reference: https://www.stata.com/statalist/archive/2011-07/msg00536.html
