### ISSUE TITLE
R libraries are not found anymore

### ISSUE THREAD

**Issue by raholler** [hmgaudecker/econ-project-templates#68]
From one day to the other (it worked this morning), I get the following error for all my R packages (for instance):

```r

Fehler in library(rjson) : es gibt kein Paket namens 'rjson'
Ausf³hrung angehalten
```
When I execute it within Rstudio, it works fine.

When I run ```python waf.py configure``` I get the following output:

```
Setting top to                           : C:\Users\rados\Documents\comp-patience
Setting out to                           : C:\Users\rados\Documents\comp-patience\bld
Checking for program 'python'            : C:\Users\rados\Anaconda3\envs\compulsory\python.exe
Checking for program 'RScript, Rscript'  : C:\Program Files\R\R-3.6.1\bin\RScript.exe
Checking for program 'sphinx-build'      : C:\Users\rados\Anaconda3\envs\compulsory\Scripts\sphinx-build.exe
Checking for program 'makeinfo'          : not found
Checking for program 'tex'               : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\tex.exe
Checking for program 'latex'             : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\latex.exe
Checking for program 'pdflatex'          : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe 
Checking for program 'xelatex'           : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\xelatex.exe
Checking for program 'bibtex'            : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\bibtex.exe
Checking for program 'dvips'             : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\dvips.exe
Checking for program 'dvipdf'            : not found
Checking for program 'ps2pdf'            : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\ps2pdf.exe
Checking for program 'makeindex'         : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\makeindex.exe
Checking for program 'pdf2ps'            : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\pdf2ps.exe
Checking for program 'makeglossaries'    : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\makeglossaries.exe
Checking for program 'tex'               : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\tex.exe
Checking for program 'latex'             : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\latex.exe
Checking for program 'pdflatex'          : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe 
Checking for program 'xelatex'           : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\xelatex.exe
Checking for program 'bibtex'            : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\bibtex.exe
Checking for program 'dvips'             : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\dvips.exe
Checking for program 'dvipdf'            : not found
Checking for program 'ps2pdf'            : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\ps2pdf.exe
Checking for program 'makeindex'         : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\makeindex.exe
Checking for program 'pdf2ps'            : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\pdf2ps.exe
Checking for program 'makeglossaries'    : C:\Users\rados\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\makeglossaries.exe
```

seems to check for some stuff twice...

**Comment by raholler** [comment]
The relevant paths in config.log:

```
Checking for program 'RScript, Rscript'
C:\Program Files\R\R-3.6.1\bin\RScript.exe
find program=['RScript', 'Rscript'] paths=['C:\\Users\\rados\\Anaconda3\\envs\\compulsory', 'C:\\Users\\rados\\Anaconda3\\envs\\compulsory\\Library\\mingw-w64\\bin', 'C:\\Users\\rados\\Anaconda3\\envs\\compulsory\\Library\\usr\\bin', 'C:\\Users\\rados\\Anaconda3\\envs\\compulsory\\Library\\bin', 'C:\\Users\\rados\\Anaconda3\\envs\\compulsory\\Scripts', 'C:\\Users\\rados\\Anaconda3\\envs\\compulsory\\bin', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0', 'C:\\Windows\\System32\\OpenSSH', 'C:\\Program Files\\Git\\cmd', 'C:\\Users\\rados\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\rados\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64', 'C:\\Users\\rados\\Anaconda3\\condabin', 'C:\\Program Files\\Sublime Text 3', 'C:\\Program Files\\R\\R-3.6.1\\bin', 'C:\\Users\\rados\\AppData\\Local\\atom\\bin', 'C:\\Users\\rados\\Documents\\R\\win-library\\3.6', '.'] var='RCMD' -> ['C:\\Program Files\\R\\R-3.6.1\\bin\\RScript.exe']
```

C:\\Users\\rados\\Documents\\R\\win-library\\3.6 is the relevant library folder, where the packages are installed.

**Comment by hmgaudecker** [comment]
> seems to check for some stuff twice...

That always happens when you load the LaTeX tool yourself and it is loaded by the Sphinx builder once more. 

Other than that, I do not quite understand. Is that the R version that you expect to find? Or should it be the one that gets installed by conda? Waf does not check for R's libraries.

**Comment by raholler** [comment]
No, the problem is that when I run waf, my R scripts do not seem to find my packages anymore. They are installed. And it worked until this morning. And when I run the scripts within R studio, it also finds the packages. So something makes waf not to find my library anymore.

The only thing I did today was to install posh-git.

**Comment by hmgaudecker** [comment]
What if you use the command line version of R by typing `RScript` in the Powershell? Does it find your packages?

**Comment by hmgaudecker** [comment]
Did you ever find out whether that was a quirk on your machine or something of wider significance?

**Comment by raholler** [comment]
Not yet, but I left it open because there might be a wider significance:

We do not know, what happens when you have a R distribution in your conda env, but you want to use packages that you cannot install via conda.

**Comment by hmgaudecker** [comment]
You just instlall them the usual way via install.packages ? Will be difficult to re-create (more or less) consistently, of course, which is what conda aims to solve. See the old code that you removed earlier this year.

You will have to make sure you install the packages into the R installed by conda. 

Could it be that above, you installed the packages in your system-wide R installation but not into the one managed by conda?

**Comment by raholler** [comment]
So I think we should add this to the documentation.

It is a way around my problem, but it does not solve the original issue. In this conda env I did not used to have r installed when the error occured. But using the conda distributed R + packages it works. 

*For future reference*:
Somehow my Rscript.exe from the command line was missing my user library path, even though my RGui did not. This solved my issue: 
https://stackoverflow.com/questions/15170399/change-r-default-library-path-using-libpaths-in-rprofile-site-fails-to-work
i.e. setting R_LIBS_USER environmental variable. 
How this happened remains a mystery and might be due to some weird interaction with conda (or not).
