### ISSUE TITLE
Very (very) minor: Comma in page headers of Sphinx PDF documentation

### ISSUE THREAD

**Issue by ThomasGraeber** [hmgaudecker/econ-project-templates#7]
The default page header line is defined in sphinx.sty is <pre> \fancyhead[LE,RO]{{\py@HeaderFamily \@title, \py@release}} </pre> so the header becomes "title, release".

In the conf.py of the template, you set the release to empty string in the latex_elements: 
<pre> # Remove the "Release ..." subtitle from the LaTeX frontpage.
    "releasename": "" </pre>
This way the default page header is "title, " with a lost comma, which is ugly. To maintain flexibility in case someone wants the release in the header, one could add the following preamble to the latex_elements:
<pre># Comment out if you want the release displayed in the header
    'preamble': r"""
        \makeatletter 
            \fancypagestyle{normal}{ 
                \fancyhf{} 
                \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}} 
                \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}} 
                \fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}} 
                \fancyhead[LE,RO]{{\py@HeaderFamily \@title}}
             } 
        \makeatother"""</pre>

**Comment by hmgaudecker** [comment]
Agreed, but it may change in future versions of Sphinx and the potential maintenance effort is a bit too high for the benefit.

If you like, you could add an item 'Formatting of the pdf documentation' to the FAQ.
