### ISSUE TITLE
Fix URL for keeping alongside the cookiecutter dialogue

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#73]
Still reads:

```
Do_you_have_https://github.com/hmgaudecker/econ-project-templates/_open_alongside_this_dialogue_or_do_you_know_exactly_what_you_are_doing? [yes]: 
```
Should be pointing to: https://econ-project-templates.readthedocs.io/en/stable/getting_started.html#configuring-your-new-project

with stable replaced by current version? Or better leave it at that?

**Comment by raholler** [comment]
da33b5ec93b5ac56d62e8a217db685a19e32fd03
