### ISSUE TITLE
Get Jupyter Kernel for environment

### ISSUE THREAD

**Issue by hmgaudecker** [hmgaudecker/econ-project-templates#76]
Previous combinations of Jupyter/conda automatically provided kernels for all available conda environments, this is not the case anymore. See this [answer](https://stackoverflow.com/questions/39604271/conda-environments-not-showing-up-in-jupyter-notebook?answertab=votes#tab-top) on SO.

We definitely need to add `ipykernel` to the environment.

Beyond that, it is probably easiest to also add the `nb_conda_kernels` to the environment, I have not been able to try that out, though.

Else, we need to do this after activating the environment:
```
python -m ipykernel install --user --name {env_name} --display-name "{env_name}"
```
See https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments

**Comment by hmgaudecker** [comment]
> Beyond that, it is probably easiest to also add the `nb_conda_kernels` to the environment, I have not been able to try that out, though.

Just tried on a different machine and it seems to work well, at least on Ubuntu. So I suppose that should do.

**Comment by raholler** [comment]
So on my machine, ipykernel is automatically installed, when jupyter lab is installed.
Installing nb_conda_kernels works on my machine, and enables full environment use in notebook.

**Comment by raholler** [comment]
so I updated the environment to contain nb_conda_kernels.

**Comment by hmgaudecker** [comment]
Thanks! Please add ipykernel, too. Better explicit than implicit...

**Comment by raholler** [comment]
Done
